on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
      service:
        required: false
        type: string
      build_type:
        required: true
        type: string
        default: package
    secrets:
      envPAT:
        required: true

env:
  SERVICE: ${{ inputs.service }}

jobs:
  npm-build:
    runs-on: gha-runner-scale-set
    steps:
      - uses: actions/checkout@v3
        with:
          repository: CoinmapTrading/actions
          token: ${{ secrets.envPAT }}
          path: coinmap-actions
      - uses: ./coinmap-actions/cloudfunction

