on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
      service:
        required: false
        type: string
      build_type:
        required: true
        type: string
        default: docker
    secrets:
      envPAT:
        required: true

jobs:
  build-docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          repository: cocdibui/actions
          token: ${{ secrets.envPAT }}
          path: coinmap-actions
      - uses: ./coinmap-actions/notification

