on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
      service:
        required: false
        type: string
      build_type:
        required: true
        type: string
        default: docker
    secrets:
      envPAT:
        required: true

env:
  SERVICE: ${{ inputs.service }}

jobs:

  build-docker:
    runs-on: self-hosted
    outputs:
      build-version: ${{ steps.build.outputs.build-version }}
      environment: ${{ steps.build.outputs.environment }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: CoinmapTrading/actions
          token: ${{ secrets.envPAT }}
          path: coinmap-actions
          ref: v0.0.1
      - id: build
        uses: ./coinmap-actions/build
      - uses: ./coinmap-actions/notification
        if: ${{ failure() }}
        with:
          environment: 'build-docker'
          version: ${{ steps.build.outputs.build-version }}
          status: "failure"
          
  deploy:
    needs: [build-docker]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          repository: CoinmapTrading/actions
          token: ${{ secrets.envPAT }}
          path: coinmap-actions
          ref: dev-ci
      - uses: actions/checkout@v3
        with:
          repository: CoinmapTrading/cm-infras
          token: ${{ secrets.envPAT }}
          path: cm-infras
      - id: deploy
        uses: ./coinmap-actions/deploy
        with:
          version: ${{needs.build-docker.outputs.build-version}}
          environment: ${{needs.build-docker.outputs.environment}}

      - uses: ./coinmap-actions/notification
        if: ${{ failure() }}
        with:
          version: ${{needs.build-docker.outputs.build-version}}
          environment: ${{needs.build-docker.outputs.environment}}
          status: "failure"

      - uses: ./coinmap-actions/notification
        if: ${{ success() }}
        with:
          version: ${{needs.build-docker.outputs.build-version}}
          environment: ${{needs.build-docker.outputs.environment}}
          status: "success"
