on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
      service:
        required: false
        type: string
      build_type:
        required: true
        type: string
        default: docker
    secrets:
      envPAT:
        required: true

env:
  SERVICE: ${{ inputs.service }}

jobs:
  build-react-stockcharts:
    if: contains(github.repository, 'star-flow')
    runs-on: self-hosted
    container: node:14.18.2-alpine
    steps:
      - uses: actions/checkout@v3
        with:
          repository: CoinmapTrading/actions
          token: ${{ secrets.envPAT }}
          path: ~/private_action/coinmap-actions
      - uses: ~/private_action/coinmap-actions/build-react-stockcharts

  build-docker:
    needs: [build-react-stockcharts]
    if: ${{ always() }}
    runs-on: self-hosted
    outputs:
      build-version: ${{ steps.build.outputs.build-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: CoinmapTrading/actions
          token: ${{ secrets.envPAT }}
          path: ~/private_action/coinmap-actions
      - id: build
        uses: ~/private_action/coinmap-actions/build

  deploy:
    runs-on: self-hosted
    needs: [build-docker]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: CoinmapTrading/actions
          token: ${{ secrets.envPAT }}
          path: ~/private_action/coinmap-actions
      - id: deploy
        uses: ~/private_action/coinmap-actions/deploy
        with:
          version: ${{needs.build-docker.outputs.build-version}}
      - uses: ~/private_action/coinmap-actions/notification
        with:
          version: ${{needs.build-docker.outputs.build-version}}
          environment: ${{ steps.deploy.outputs.environment }}