on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  share_build_workflow:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          repository: cocdibui/actions
          token: ${{ secrets.envPAT }}
          path: coinmap-actions
      - uses: ./coinmap-actions/notification

